version: '3.8'

services:
  app:
    cap_drop:
      - ALL
    build:
      context: .
      args:
        DOCKER_USER: "${DOCKER_USER}"
        DOCKER_UID: "${DOCKER_UID}"
        DOCKER_GID: "${DOCKER_GID}"
        DOCKER_TZ: "${DOCKER_TZ}"
        DOCKER_PORT: "${DOCKER_PORT}"
    volumes:
      - ./config:/mnt/skychat/config
      - ./backups:/mnt/skychat/backups
      - ./storage:/mnt/skychat/storage
      - ./gallery:/mnt/skychat/gallery
      - ./uploads:/mnt/skychat/uploads
    ports:
        - "${DOCKER_PORT}:${DOCKER_PORT}"
