version: '3.5'

services:
  app:
    cap_drop:
      - ALL
    build:
      context: .
      args:
        UNAME: ${DOCKER_UNAME}
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
        DOCKER_TZ: "${DOCKER_TZ}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./avatars:/var/skychat/avatars
      - ./backups:/var/skychat/backups
      - ./config:/var/skychat/config:ro
      - ./database:/var/skychat/database
      - ./scripts:/var/skychat/scripts:ro
      - ./stickers:/var/skychat/stickers
      - ./storage:/var/skychat/storage
      - ./uploads:/var/skychat/uploads
    ports:
        - "${DOCKER_PORT}:${DOCKER_PORT}"
